# This is a basic workflow to help you get started with Actions

name: Website Tests

on: [push, pull_request] # TODO: make this only pushes on master and pull requests

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install Pa11y
      run: npm install --global pa11y-ci
    
    - name: Get Deployment URL
      uses: dorshinar/get-deployment-url@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Test Accessibility
      run: pa11y-ci --sitemap ${{ needs.get_deployment_url.outputs.deployment }}/sitemap.xml
      

