name: Website Tests

on:
  push:
    branches: [master, draft]
  pull_request:

jobs:

  accessibility:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install Pa11y
      run: npm install --global pa11y-ci
    
    - name: Get Deployment URL
      id: get_deployment_url
      uses: dorshinar/get-deployment-url@v1.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Test Accessibility
      run: pa11y-ci --sitemap ${{ steps.get_deployment_url.outputs.deployment }}/sitemap.xml --sitemap-find "^/" --sitemap-replace "${{ steps.get_deployment_url.outputs.deployment }}/"


  proofer:
    name: HTML Proofer
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get Deployment URL
        id: get_deployment_url
        uses: dorshinar/get-deployment-url@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2.4.11
        with:
          extended: true
      - name: Build site
        run: hugo --buildDrafts --baseURL=${{ steps.get_deployment_url.outputs.deployment }}
      
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install HTML Proofer
        run: gem install html-proofer
      - name: Run HTML Proofer
        # adapted from https://github.com/cibuilds/hugo#using-on-circleci
        run: htmlproofer ./public --allow-hash-href --check-html --empty-alt-ignore --disable-external
