name: Website Tests

on:
  push:
    branches: [master, draft]
  pull_request:

jobs:

  accessibility:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install Pa11y
      run: npm install --global pa11y-ci
    
    - name: Get Deployment URL
      id: get_deployment_url
      uses: dorshinar/get-deployment-url@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Test Accessibility
      run: pa11y-ci --sitemap ${{ steps.get_deployment_url.outputs.deployment }}/sitemap.xml
